name: Correctness Test for goid

on:
  workflow_dispatch:

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21', '1.22', '1.23', '1.24']
        arch: [amd64, arm64, 386, armv7]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure architecture
        run: |
          case ${{ matrix.arch }} in
            amd64)
              echo GOARCH=amd64 >> "$GITHUB_ENV"
              ;;
            arm64)
              echo GOARCH=arm64 >> "$GITHUB_ENV"
              ;;
            386)
              echo GOARCH=386 >> "$GITHUB_ENV"
              ;;
            armv7)
              echo GOARCH=arm >> "$GITHUB_ENV"
              echo GOARM=7 >> "$GITHUB_ENV"
              ;;
          esac

      - name: Install QEMU (non-amd64)
        if: matrix.arch != 'amd64'
        uses: docker/setup-qemu-action@v3

      - name: Build
        run: go build -v ./...

      - name: Run tests (native)
        if: matrix.arch == 'amd64'
        run: go test -v -bench=. ./...

      - name: Run tests (emulated)
        if: matrix.arch != 'amd64'
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: bullseye
          dockerRunArgs: |
            --volume "${PWD}:/go/src/app"
          run: |
            cd /go/src/app
            go test -v -bench=. ./...

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21', '1.22', '1.23', '1.24']
        arch: [amd64, 386]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure architecture
        run: |
          if ("${{ matrix.arch }}" -eq "amd64") { echo "GOARCH=amd64" | Out-File -FilePath $env:GITHUB_ENV -Append }
          elseif ("${{ matrix.arch }}" -eq "386") { echo "GOARCH=386" | Out-File -FilePath $env:GITHUB_ENV -Append }

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -bench=. ./...
